#!/usr/bin/expect -f

spawn ./ex19

# How long should the script wait between expect continues
set timeout 1

set count [lindex $argv 0]
if { $count == "" } { set count 10 }
while {$count > 0 } {
    # Gimme back my prompt
    expect ">"

    # Where can I go?
    send "l\n"

    # list for options to go next
    set go {};
    # what did the game say?
    expect {
        "NORTH" {
            lappend go "n"
            exp_continue -continue_timer
        }   
        "SOUTH" {
            lappend go "s"
            exp_continue -continue_timer
        }   
        "EAST" {
            lappend go "e"
            exp_continue -continue_timer
        }   
        "WEST" {
            lappend go "w"
            exp_continue -continue_timer
        }
        default { 
        }
    }
    # randomize index direction from the ones avaialable
    set index [expr {int(rand()*[llength $go])}]
    # move in the randomized direction
    send "[lindex $go $index]\n" 
    
    # wait for prompt 
    expect ">"
    
    # one less move 
    set count [expr $count-1];
}

close
#interact
